name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 1.0.0
homepage: https://github.com/GianSandoval5/voice_message_player


environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  syncfusion_flutter_sliders: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


